<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IncludeSource>true</IncludeSource>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.0" />
        <PackageReference Include="Ballware.Shared.Data.Ef" Version="1.2.0-alpha.14" />
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
        <PackageReference Include="Npgsql" Version="10.0.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ballware.Generic.Caching\Ballware.Generic.Caching.csproj" />
        <ProjectReference Include="..\Ballware.Generic.Data.Caching\Ballware.Generic.Data.Caching.csproj" />
        <ProjectReference Include="..\Ballware.Generic.Data.Ef\Ballware.Generic.Data.Ef.csproj" />
        <ProjectReference Include="..\Ballware.Generic.Data\Ballware.Generic.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
