// <auto-generated />
using System;
using Ballware.Generic.Data.Ef.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ballware.Generic.Data.Ef.Postgres.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ballware.Generic.Data.Persistables.TenantConnection", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("connection_string");

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Schema")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_tenant_connection");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_connection_uuid");

                    b.ToTable("tenant_connection", (string)null);
                });

            modelBuilder.Entity("Ballware.Generic.Data.Persistables.TenantEntity", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_tenant_entity");

                    b.HasIndex("TenantId", "Entity")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_entity_tenant_id_entity");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_entity_tenant_id_uuid");

                    b.ToTable("tenant_entity", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
