name: Docker Image Latest

on:
  push:
    branches: ['develop']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            8.0
      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool
      - name: Fetch GitVersion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/.
          file: src/Ballware.Generic.Service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ballware/ballware-generic-service:latest
            ghcr.io/ballware/ballware-generic-service:${{ env.GitVersion_SemVer }}  